# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-10-31 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=32, verbose_name='槽位')),
                ('pd_type', models.CharField(max_length=32, verbose_name='类型')),
                ('capacity', models.CharField(max_length=32, verbose_name='容量')),
                ('model', models.CharField(max_length=32, verbose_name='型号')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Server', verbose_name='服务器')),
            ],
        ),
    ]
