# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-10-31 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_assetsrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='last_date',
            field=models.DateField(null=True, verbose_name='最近汇报时间'),
        ),
    ]
