# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-04 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191104_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='status',
            field=models.IntegerField(choices=[(1, '上线'), (2, '下线')], default=1, verbose_name='状态'),
        ),
    ]
